### ISSUE TITLE
Return Affected Rows

### ISSUE THREAD

**Issue by votemike** [yadakhov/insert-on-duplicate-key#12]
Would it be possible to somehow grab the number of rows affected? At the moment all the methods return a bool whereas I'd like to know if an INSERT was actually done or ignored. It would be easy to use Laravel's affectingStatement() method, but that would change the API of your code.

Would it be possible to make this breaking change and bump the version number?

Or possibly save the number of affected rows and add a method to grab that value.

I should be able to do the work if you like.

**Comment by yadakhov** [comment]
Sure.  Do a PR and I'll merge.

Note that affected rows counts as 2 for duplicates.

http://stackoverflow.com/questions/3747314/why-are-2-rows-affected-in-my-insert-on-duplicate-key-update

**Comment by stebogit** [comment]
@votemike I'm not sure how to use this feature when inserting multiple rows at once, and I believe there is at least an imprecision in the docs.
The current documentation says:
```php
/*
* @return int 0 if row is not changed, 1 if row is inserted, 2 if row is updated
*/
public static function insertOnDuplicateKey(array $data, array $updateColumns = null)
```
however with multiple inserts/updates the output is the sum of the single affected-rows values.
Now I get that for a single operation `0-1-2` values help to discriminate what happened, but here, from the sum, how do I define how many rows have been inserted and how many updated?

It would be nice to return an array like 
```php
[ 'updates' => 2, 'inserts' => 17 ]
```
but is it even possible, I mean does MySQL even allow to discriminate between insert/update in a big single statement like the one the method creates?

Thanks, and thank you @yadakhov for the great tool! 👍

**Comment by votemike** [comment]
Wow, it's been a while since I did this work. @vifer do you still work with this? Any idea about @stebogit 's question?
