### ISSUE TITLE
Extending Your Class

### ISSUE THREAD

**Issue by jgcl** [yadakhov/insert-on-duplicate-key#16]
Hello. I had the need to work with json in mysql and in the case of the insert I needed to use json_merge. I removed the array validation from the $ updateColumns variable and changed the buildInsertOnDuplicateSql method to:

>protected static function buildInsertOnDuplicateSql(array $data, $updateColumns = null)
>{
>   $first = static::getFirstRow($data);
>
>   $sql  = 'INSERT INTO &#96;' . static::getTablePrefix() . static::getTableName() . '&#96;(' . static::getColumnList($first) . ') VALUES' . PHP_EOL;
>
>   $sql .=  static::buildQuestionMarks($data) . PHP_EOL;
>
>   $sql .= 'ON DUPLICATE KEY UPDATE ';
>
>   if (empty($updateColumns)) {
>       $sql .= static::buildValuesList($first);
>   } else if(is_array($updateColumns)) {
>       $sql .= static::buildValuesList(array_combine($updateColumns, $updateColumns));
>   } else if(is_string($updateColumns)) {
>       $sql .= $updateColumns;
>   }
>
>   return $sql;
>}

Thanks for code. I love you hahahah

**Comment by yadakhov** [comment]
Glad you found the package useful.
