### ISSUE TITLE
Incremental values on UPDATE

### ISSUE THREAD

**Issue by nonsapiens** [yadakhov/insert-on-duplicate-key#17]
Hi there,

What would be really amazing would be to allow incremental values on update, something like this INSERT:

```
INSERT INTO table 
  (a, counter_elem) 
VALUES 
  (1, 1),
  (2, 1)
ON DUPLICATE KEY UPDATE counter_elem = counter_elem + 1;
```
In this example, with counter_elem incrementing by one on each duplicate.  In my project, I have an aggregation table that aggregates the values of a transaction table.  If your function were able to indicate that a value being passed for update was potentially incrementable, that would be *amazing* !

**Comment by yadakhov** [comment]
I can write code to look up the `updatedColumns` array.  If the user pass in a "string" key associative array it will use the right hand side.

`insertOnDuplicateKey(array $data, array $updateColumns = null)`

For you case the $updatedColumns should look like:

`$updatedColumns = ['counter_elem' => 'counter_elem + 1']`

I'll make the code change when I have time later today.

**Comment by yadakhov** [comment]
@nonsapiens  I pushed the code for the enhancement.  Can you give it a quick test by changing your composer.json 

"yadakhov/insert-on-duplicate-key": "dev-master"

Once more testing is done I can create a new release version v1.2.0

**Comment by nonsapiens** [comment]
Sorry mate been on leave for some time.  Let me give this a try, see how it goes!

**Comment by ronnievisser** [comment]
when will this gets version 1.2?

**Comment by yadakhov** [comment]
I apologize.  Forgot to create a new release.  1.2 is done.

**Comment by ronnievisser** [comment]
Perfect! Thanks for your work!

**Comment by nonsapiens** [comment]
Sorry I realised I forgot to reply to this from way back:  thanks for this, works well ...
