### ISSUE TITLE
Multiple Scheme?

### ISSUE THREAD

**Issue by wwardaww** [yadakhov/insert-on-duplicate-key#23]
This trait doesn't support multiple scheme, i change it but i can't open pull req. , 

I change 

``
$sql  = 'REPLACE INTO `' . static::getTablePrefix().... 
`` 

To :

    protected static function buildReplaceSql(array $data,$scheme=null)
         {

        $first = static::getFirstRow($data);
            if($scheme == null)
                 $scheme = env('DB_DATABASE');

      $sql  = "REPLACE INTO `".$scheme.'`.`' . static::getTablePrefix()...

so i forked [HERE](https://github.com/wwardaww/insert-on-duplicate-key)

**Comment by yadakhov** [comment]
Uou can setup a connection in the model to use multiple databases aka scheme.

https://stackoverflow.com/questions/28985472/change-database-connection-in-laravel-model
