### ISSUE TITLE
Anyway to get this to work with the query builder instead of a model?

### ISSUE THREAD

**Issue by benjivm** [yadakhov/insert-on-duplicate-key#27]
I'd like to be able to use this with `DB::table('my-table')->insertOnDuplicateKey($data);`, is that possible? I'm not sure how to make the `DB::class` use a trait.

**Comment by MarcTroesken** [comment]
Yeah that is what I need! Exactly the same. Any ideas on that ?

**Comment by yadakhov** [comment]
To be honest, I haven't looked into it making it work with query builder.  The code originally came from just a plain mysqli helper class for insert on duplicate key.

**Comment by IllyaMoskvin** [comment]
I've been using a modified version of this: 

https://gist.github.com/VinceG/0fb570925748ab35bc53f2a798cb517c

It overrides the connection for `mysql` to make these commands work with the query builder.
