### ISSUE TITLE
More complex update logic

### ISSUE THREAD

**Issue by alberto-bottarini** [yadakhov/insert-on-duplicate-key#28]
Hi, sometimes I need to perform some "complex" logic instead of a simple update in a ON DUPLICATE KEY query, for example

    ON DUPLICATE KEY UPDATE
    `counter` = `counter` + VALUES(`counter`)

How can I achieve that?

Something like this will be a good solution imho:

    Model::insertOnDuplicateKey($data, [
        'counter' => 'sum',
        'last_name' => 'replace,
    ]); @

**Comment by amayer-glei** [comment]
I suggest the option to pass DB::raw()
