### ISSUE TITLE
How to fill time field data in table?

### ISSUE THREAD

**Issue by cwl168** [yadakhov/insert-on-duplicate-key#29]
The table contains 'create_time' and 'update_time' fields, how to automatically fill the data of these two fields?

**Comment by eKevinHoang** [comment]
@yadakhov 
I got the same issue and DB:raw('NOW()') also not working.

**Comment by yadakhov** [comment]
You can move the NOW() into PHP application level.
```

$now = date('Y-m-d H:i:s');

$row = ['id' => 1, ..., 'create_time' => $now, 'update_time' => $now];

Model::insertOnDuplicateKey($row);
```

**Comment by yadakhov** [comment]
```$now = date('Y-m-d H:i:s');$row = ['id' => 1, ..., 'create_time' => $now, 'update_time' => $now];Model::insertOnDuplicateKey($row);```

**Comment by yadakhov** [comment]
```$now = date('Y-m-d H:i:s');$row = ['id' => 1, ..., 'create_time' => $now, 'update_time' => $now];Model::insertOnDuplicateKey($row);```

**Comment by eKevinHoang** [comment]
@yadakhov Your workaround is not works, the error message as below.

Errror: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '10:59:24' at line 3 (SQL: INSERT INTO `user_relations`(`customer_user_id`,`user_id`,`created_at`,`updated_at`) VALUES (1012,338,2018-10-04 10:59:24,2018-10-04 10:59:24) ON DUPLICATE KEY UPDATE updated_at = 2018-10-04 10:59:24)

My Laravel version: 5.7
