### ISSUE TITLE
Order of data key => value pairs

### ISSUE THREAD

**Issue by grazinskis** [yadakhov/insert-on-duplicate-key#33]
I think the documentation should mention that the order of key value pairs is important. If it's different for one record, insert/update will yield unexpected results. For example: 

```php
    $users = [
        ['id' => 1, 'email' => 'user1@email.com', 'name' => 'User One'],
        ['email' => 'user2@email.com', 'id' => 2, 'name' => 'User Two'],
        ['email' => 'user3@email.com', 'name' => 'User Three', 'id' => 3],
    ];
```

Each array has the same keys but in different order. After [array_values](https://github.com/yadakhov/insert-on-duplicate-key/blob/a116207231698747fb4b8d927fc088ccec2c5dd2/src/InsertOnDuplicateKey.php#L223) runs, the keys turn into integer indexes, which disregard which value was attached to which key. I think this should be either noted in the docs or dealt with in the code (now I run ksort on each array).

**Comment by n0099** [comment]
+1

**Comment by yadakhov** [comment]
Thanks.  The documentation is added.

https://github.com/yadakhov/insert-on-duplicate-key/commit/46a7fa13924f6c2e6db93cbd2183c4898732b950
