### ISSUE TITLE
Support unique keys

### ISSUE THREAD

**Issue by riley-van-hengstum** [yadakhov/insert-on-duplicate-key#4]
The INSERT ... ON DUPLICATE KEY syntax also works with unique keys (instead of primary keys) but your code doesn't because of the primary key check (checkPrimaryKeyExists).

**Comment by yadakhov** [comment]
Yes, you are right.  Primary key doesn't need to be checked in case of a unique key.

I'm going to remove the check and put the onus on the user.

**Comment by yadakhov** [comment]
Released in v0.0.6
