### ISSUE TITLE
does not support sqlite for insert ignore

### ISSUE THREAD

**Issue by matgargano** [yadakhov/insert-on-duplicate-key#8]
SQLite uses the syntax

INSERT OR IGNORE instead of INSERT IGNORE

**Comment by yadakhov** [comment]
This package will only support MySQL.  Feel free to fork and support SQLite.

**Comment by melihovv** [comment]
Add sqlite support for insert ignore https://github.com/melihovv/insert-on-duplicate-key/commit/ebc2f66218512835307fce5688c961a4bbe0621e
