### ISSUE TITLE
use Model->connection instead of Illuminate\Support\Facades\DB;

### ISSUE THREAD

**Issue by aldas** [yadakhov/insert-on-duplicate-key#9]
Maybe it would be better to use Model class property $connection instead of Facade.  

For example I am using Eloquent with Slim framework and instead of using Illuminate\Support\Facades\DB I have Illuminate\Database\Capsule\Manager as DB (http://stackoverflow.com/a/29500701) but if this trait tries to use Support\Facades\DB i'm in a trouble. 

this all is not necessary as Model itself is aware of its connection ($connection) so it would be better to use it instead of having direct dependency to Illuminate\Support\Facades package

**Comment by aldas** [comment]
so you could add

```
    protected static function getConnection()
    {
        $class = get_called_class();
        return (new $class())->getConnection();
    }
```

and call it when doing query

```
        return self::getConnection()->statement($sql, $data);
```

and remove dependency to DB facade `"illuminate/support": "^5.1",`

**Comment by yadakhov** [comment]
Great idea. I will implement when I have some free time.  If you like to implement yourself feel free to do a Pull Request.

**Comment by aldas** [comment]
also I think that new class instance creation can be replaced

so
```
$class = get_called_class();
return (new $class())->getConnection();
```
can be replaced with

```
$class = static::class;
return $class::getConnection();
```

works on PHP 5.5+
 http://sandbox.onlinephpfunctions.com/code/b59a11fe4e3f20b0bfdbc27c5b50ca300f4c718f


NB: illuminate/database requires PHP 5.5.9+ (5.1 branch) but this lib has  `"php": ">=5.4.0"` in composer.json
